### ISSUE TITLE
Проблема с подключением

### ISSUE THREAD

**Issue by vane0kravitz** [joni-jones/yii2-wschat#14]
Привет, есть не большая проблема, все сделал по инструкции, запускаю сервер но сообщения не выводятся, никак не реагирует, подскажи что может помочь или куда копать, спасибо

**Comment by vane0kravitz** [comment]
![image](https://cloud.githubusercontent.com/assets/13285932/11591895/df27f150-9aa3-11e5-8eee-972dc4d55a00.png)

**Comment by vane0kravitz** [comment]
view:

![image](https://cloud.githubusercontent.com/assets/13285932/11591945/4733edd0-9aa4-11e5-9273-38ec00ecf9bb.png)

**Comment by vane0kravitz** [comment]
коннект к базе:
![image](https://cloud.githubusercontent.com/assets/13285932/11592605/37d2bcc8-9aa8-11e5-899c-4f2ea8f41b17.png)

**Comment by vane0kravitz** [comment]
logs info 
![image](https://cloud.githubusercontent.com/assets/13285932/11593274/11aad8e2-9aac-11e5-96f6-001e4d95a564.png)

**Comment by YevSent** [comment]
Привет, так в консоли хрома куча ошибок, судя по всему ни стили ни js нормально не подгрузились. Посмотрите грузятся ли все js + перезапустить сервер и почистить куки

**Comment by vane0kravitz** [comment]
pnotify нужен?
может это из за версии?
dev-master скачаю посмотрю
![image](https://cloud.githubusercontent.com/assets/13285932/11593866/5472d73a-9aaf-11e5-93b4-697283783ee5.png)

**Comment by vane0kravitz** [comment]
(((
![image](https://cloud.githubusercontent.com/assets/13285932/11593886/76ebe91e-9aaf-11e5-8802-c674f820ec70.png)

**Comment by vane0kravitz** [comment]
pnotify подгрузил но 
![image](https://cloud.githubusercontent.com/assets/13285932/11594263/ace6abce-9ab1-11e5-99ab-659acbf34cc5.png)

**Comment by vane0kravitz** [comment]
это когда сообщение отправляю

**Comment by YevSent** [comment]
Куки пробовали чистить после перезапуска сервер сокета? Пользователь есть в списке?

**Comment by vane0kravitz** [comment]
как это сделать?

**Comment by YevSent** [comment]
С помощью консоли разработчика броузера

**Comment by vane0kravitz** [comment]
тут еще когда перезапустил
![image](https://cloud.githubusercontent.com/assets/13285932/11594371/49e18840-9ab2-11e5-9c03-4d8e4cbf1719.png)

**Comment by YevSent** [comment]
Ошибка говорит сама за себя, порт уже занят

**Comment by vane0kravitz** [comment]
вижу) сейчас исправлю

**Comment by vane0kravitz** [comment]
какой порт должен быть тут?
![image](https://cloud.githubusercontent.com/assets/13285932/11594745/63950eb8-9ab4-11e5-835e-25f320e62ea9.png)
![image](https://cloud.githubusercontent.com/assets/13285932/11594751/68e79d9a-9ab4-11e5-9b34-3fa41087716c.png)

**Comment by vane0kravitz** [comment]
я 8082 перебрасываю на 80

**Comment by YevSent** [comment]
зачем Вы что-то перебрасываете на 80? это дефолтный порт для апача

**Comment by vane0kravitz** [comment]
проект на виртуалке через vagrant

**Comment by YevSent** [comment]
а зачем 8082 пробрасываете на 80?

**Comment by vane0kravitz** [comment]
8080 же занят

**Comment by vane0kravitz** [comment]
![image](https://cloud.githubusercontent.com/assets/13285932/11594902/40c020d4-9ab5-11e5-82dc-3284451b8e26.png)

**Comment by YevSent** [comment]
так зачем что-то пробрасывать на 80 порт? для виджета и на бекенде ставится порт только для сокет соединения

**Comment by vane0kravitz** [comment]
из за чего может возникать ошибка c  set?
![image](https://cloud.githubusercontent.com/assets/13285932/11595035/10322bc8-9ab6-11e5-9ec4-0b83fc7bfde4.png)

**Comment by YevSent** [comment]
Попробуйте почистить куки

**Comment by vane0kravitz** [comment]
не помогло(

**Comment by YevSent** [comment]
Добавьте пожалуйста весь стек трейс js ошибки

**Comment by vane0kravitz** [comment]
![image](https://cloud.githubusercontent.com/assets/13285932/11595952/d36bc4f6-9aba-11e5-9fde-4e104a26757c.png)

**Comment by YevSent** [comment]
Не удалось воспроизвести Вашу проблему, скорее всего у Вас что-то не так с авторизацией пользователя. Модель устанавливается на https://github.com/joni-jones/yii2-wschat/blob/master/assets/js/views/chat.js#L13, у Вас по какой-то причине не срабатывает этот ивент.

**Comment by vane0kravitz** [comment]
Спасибо за советы, посмотрю может что то с авторизацией поможет

**Comment by vane0kravitz** [comment]
привет, сделал на чистом yii2, при добавлении нового пользователя: 
![image](https://cloud.githubusercontent.com/assets/13285932/11666070/3b49fe40-9df3-11e5-9582-d424baf7b9d4.png)

**Comment by YevSent** [comment]
Смотрите что у Вас в логах

**Comment by vane0kravitz** [comment]
Там пусто

**Comment by YevSent** [comment]
Как настроить логирование указано в ридми.

**Comment by vane0kravitz** [comment]
Я настроил логирование перед тем как смотреть его

**Comment by vane0kravitz** [comment]
Из инфо там только 2 уведомления о сессии

**Comment by khikmatullaev** [comment]
У меня такая же ошибка выходит. Есть решение этой проблемы?

**Comment by MichakRoman** [comment]
такая вот ошибка в консоли браузера, запрос юзернейма проходит после этого ничего, как понимаю не коннектиться к чату, но почему?
вылетает на функции Chat.Room.prototype.onMessage 

TypeError: Cannot read property 'Connect to chat' of undefined
    at Object.Helper.t (http://domain.com/assets/2d4472a/js/helper.js:20:33)
    at Object.<anonymous> (http://domain.com/assets/2d4472a/js/chat-room.js:54:36)
    at f (http://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone-min.js:1:2179)
    at Object.trigger (http://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone-min.js:1:1452)
    at Chat.Room.onMessage (http://domain.com/assets/2d4472a/js/chat-room.js:106:23)
    at WebSocket.self.conn.onmessage (http://domain.com/assets/2d4472a/js/chat-room.js:91:18)
